Repository irisnet/irishub, pull requests merged in 2018-12, with the labels that each got.

#811 R4R: add guardian doc and update gov doc
  docs/.vuepress/config.js
  docs/features/governance.md
  docs/features/guardian.md
  docs/zh/features/governance.md
  docs/zh/features/guardian.md
  modules/gov/handler.go
Labels: documentation

#803 edit docs on develop
  docs/cli-client/bank/README.md
  docs/cli-client/bank/account.md
  docs/cli-client/bank/broadcast.md
  docs/cli-client/bank/send.md
  docs/cli-client/bank/sign.md
  docs/cli-client/keys/show.md
  docs/cli-client/tendermint/README.md
  docs/cli-client/tendermint/show-address.md
  docs/cli-client/tendermint/show-node-id.md
  docs/cli-client/tendermint/show-validator.md
Labels: documentation

#819 R4R: Refactor client and client tests
  Makefile
  client/bank/cli/sendTx.go
  client/bank/cli/sign.go
  client/bank/lcd/sendtx.go
  client/bank/lcd/sign.go
  client/distribution/cli/sendtx.go
  client/distribution/lcd/sendtx.go
  client/gov/cli/sendtx.go
  client/gov/lcd/sendtx.go
  client/guardian/cli/sendtx.go
  client/record/cli/sendtx.go
  client/record/lcd/sendtx.go
  client/service/cli/sendtx.go
  client/service/lcd/sendtx.go
  client/slashing/cli/sendtx.go
  client/slashing/lcd/sendtx.go
  client/stake/cli/sendtx.go
  client/stake/lcd/sendtx.go
  client/upgrade/cli/sendtx.go
  client/utils/rest.go
  client/utils/txcontext.go
  client/utils/utils.go
  server/init/testnet.go
  tests/cli/bank_test.go
  tests/cli/distribution_test.go
  tests/cli/gov_test.go
  tests/cli/guardian_test.go
  tests/cli/iparam_test.go
  tests/cli/irismon_test.go
  tests/cli/record_test.go
  tests/cli/service_test.go
  tests/cli/stake_test.go
  tests/cli/upgrade_test.go
  tests/cli/utils.go
Labels: client

#820 R4R: add guardian doc for v0.8
  docs/.vuepress/config.js
  docs/features/guardian.md
  docs/zh/features/guardian.md
Labels: documentation

#821 add unjail docs
  docs/cli-client/stake/unjail.md
  docs/zh/cli-client/stake/unjail.md
Labels: documentation

#812 Prepare Docs in Release0.8
  docs/cli-client/bank/account.md
  docs/cli-client/bank/broadcast.md
  docs/cli-client/bank/send.md
  docs/cli-client/bank/sign.md
  docs/cli-client/keys/show.md
  docs/cli-client/stake/delegate.md
  docs/cli-client/stake/unjail.md
  docs/cli-client/tendermint/README.md
  docs/cli-client/tendermint/show-address.md
  docs/cli-client/tendermint/show-node-id.md
  docs/cli-client/tendermint/show-validator.md
  docs/get-started/Full-Node.md
  docs/get-started/Install-the-Software.md
  docs/get-started/Validator-Node.md
  docs/introduction/README.md
  docs/introduction/irisnet-intro.md
  docs/software/README.md
  docs/software/cli-client.md
  docs/software/light-client.md
  docs/software/node.md
  docs/zh/cli-client/README.md
  docs/zh/cli-client/bank/README.md
  docs/zh/cli-client/bank/account.md
  docs/zh/cli-client/bank/coin-type.md
  docs/zh/cli-client/gov/README.md
  docs/zh/cli-client/gov/deposit.md
  docs/zh/cli-client/gov/pull-params.md
  docs/zh/cli-client/gov/query-deposit.md
  docs/zh/cli-client/gov/query-deposits.md
  docs/zh/cli-client/gov/query-params.md
  docs/zh/cli-client/gov/query-proposal.md
  docs/zh/cli-client/gov/query-proposals.md
  docs/zh/cli-client/gov/query-tally.md
  docs/zh/cli-client/gov/query-vote.md
  docs/zh/cli-client/gov/query-votes.md
  docs/zh/cli-client/stake/unjail.md
  docs/zh/cli-client/status/README.md
  docs/zh/cli-client/upgrade/README.md
  docs/zh/cli-client/upgrade/submit-switch.md
  docs/zh/get-started/Full-Node.md
  docs/zh/get-started/Install-the-Software.md
  docs/zh/get-started/Validator-Node.md
  docs/zh/introduction/README.md
  docs/zh/introduction/irisnet-intro.md
  docs/zh/software/README.md
  docs/zh/software/cli-client.md
  docs/zh/software/node.md
Labels: documentation

#822 R4R: fix genesis doc
  docs/features/basic-concepts/genesis-file.md
  docs/zh/features/basic-concepts/genesis-file.md
Labels: documentation

#825 R4R: bug fix for msg validate and err msg
  modules/auth/ante.go
  modules/bank/keeper.go
  modules/gov/errors.go
  modules/service/handler.go
  modules/service/keeper.go
  modules/service/msgs.go
  modules/stake/types/errors.go
Labels: bug

#836 R4R: Ensure moniker is not empty in init comand
  client/stake/cli/query.go
  client/stake/cli/sendtx.go
  client/stake/lcd/utils.go
  server/init/init.go
Labels: bug

#838 R4R: Ensure printing reponse in broadcast tx
  client/bank/cli/broadcast.go
Labels: enhancement

#835 R4R: fix href and tags
  docs/cli-client/gov/deposit.md
  docs/cli-client/gov/submit-proposal.md
  docs/cli-client/gov/vote.md
  docs/cli-client/record/submit.md
  docs/cli-client/service/bind.md
  docs/cli-client/service/call.md
  docs/cli-client/service/define.md
  docs/cli-client/service/disable.md
  docs/cli-client/service/enable.md
  docs/cli-client/service/refund-deposit.md
  docs/cli-client/service/refund-fees.md
  docs/cli-client/service/respond.md
  docs/cli-client/service/update-binding.md
  docs/features/service.md
  docs/zh/cli-client/gov/deposit.md
  docs/zh/cli-client/gov/submit-proposal.md
  docs/zh/cli-client/gov/vote.md
  docs/zh/cli-client/record/submit.md
  docs/zh/cli-client/service/bind.md
  docs/zh/cli-client/service/call.md
  docs/zh/cli-client/service/define.md
  docs/zh/cli-client/service/disable.md
  docs/zh/cli-client/service/enable.md
  docs/zh/cli-client/service/refund-deposit.md
  docs/zh/cli-client/service/refund-fees.md
  docs/zh/cli-client/service/respond.md
  docs/zh/cli-client/service/update-binding.md
  docs/zh/cli-client/service/withdraw-fees.md
  docs/zh/features/service.md
Labels: documentation

#839 R4R: Make unit_test pass
  modules/gov/proposal_upgrade.go
Labels: bug

#843 R4R: Add parameter checking for export state
  server/export.go
Labels: bug

#845 IRISHUB694:Fix the query bug
  client/gov/cli/query.go
  client/gov/cli/sendtx.go
  client/gov/lcd/query.go
  modules/gov/errors.go
  modules/gov/queryable.go
Labels: client

#850 R4R: fix the upgrade execute
  modules/gov/proposal_upgrade.go
  modules/upgrade/keeper.go
  modules/upgrade/keeper_keys.go
Labels: software-upgrade

#854 R4R: refactor auth and bank
  app/v0/protocol_v0.go
  modules/auth/keeper.go
  modules/bank/keeper.go
  modules/bank/keeper_test.go
Labels: enhancement, token-economics

#855 R4R: Finish querying the upgrade signal status
  client/upgrade/cli/query.go
  cmd/iriscli/main.go
  docs/cli-client/upgrade/README.md
  docs/cli-client/upgrade/query-signals.md
  docs/zh/cli-client/upgrade/README.md
  docs/zh/cli-client/upgrade/query-signals.md
  modules/upgrade/keeper_keys.go
Labels: software-upgrade

#856 R4R: remove the text proposal and update docs
  app/v0/genesis.go
  docs/cli-client/gov/submit-proposal.md
  docs/features/governance.md
  docs/features/upgrade.md
  docs/zh/cli-client/gov/submit-proposal.md
  docs/zh/features/governance.md
  docs/zh/features/upgrade.md
  modules/gov/keeper.go
  modules/gov/proposals.go
  modules/gov/simulation/msgs.go
Labels: governance

#857 fix unit test and skip gov cli test until the gov refactor finished
  modules/gov/simulation/msgs.go
  tests/cli/gov_test.go
Labels: governance

#861 R4R: Make gov data types codec wires usable across different protocol versions
  app/app.go
  app/v0/protocol_v0.go
  client/gov/cli/query.go
  client/gov/cli/sendtx.go
  client/gov/lcd/query.go
  client/gov/lcd/sendtx.go
  docs/cli-client/upgrade/query-signals.md
  docs/zh/cli-client/upgrade/query-signals.md
  modules/gov/codec.go
  modules/gov/execute.go
  modules/gov/genesis.go
  modules/gov/handler.go
  modules/gov/keeper.go
  modules/gov/keeper_keys.go
  modules/gov/msgs.go
  modules/gov/proposal_halt.go
  modules/gov/proposal_params.go
  modules/gov/proposal_upgrade.go
  modules/gov/queryable.go
  modules/gov/simulation/msgs.go
  modules/gov/simulation/sim_test.go
  modules/gov/tally.go
  modules/gov/test_common.go
  modules/mock/app.go
  tools/prometheus/governance/metrics.go
  types/gov/codec.go
  types/gov/config_file.go
  types/gov/depositsvotes.go
  types/gov/errors.go
  types/gov/params/gov_params.go
  types/gov/params/gov_params_test.go
  types/gov/params/util.go
  types/gov/proposal_halt.go
  types/gov/proposal_params.go
  types/gov/proposal_taxusage.go
  types/gov/proposal_upgrade.go
  types/gov/proposals.go
Labels: enhancement, governance

#858 R4R: Move gov types to types/gov
  app/app.go
  app/v0/protocol_v0.go
  client/gov/cli/query.go
  client/gov/cli/sendtx.go
  client/gov/lcd/query.go
  client/gov/lcd/sendtx.go
  client/gov/utils.go
  modules/gov/codec.go
  modules/gov/execute.go
  modules/gov/genesis.go
  modules/gov/handler.go
  modules/gov/keeper.go
  modules/gov/keeper_keys.go
  modules/gov/msgs.go
  modules/gov/proposal_halt.go
  modules/gov/proposal_params.go
  modules/gov/proposal_upgrade.go
  modules/gov/queryable.go
  modules/gov/simulation/msgs.go
  modules/gov/simulation/sim_test.go
  modules/gov/tally.go
  modules/gov/test_common.go
  modules/mock/app.go
  tools/prometheus/governance/metrics.go
  types/gov/codec.go
  types/gov/config_file.go
  types/gov/depositsvotes.go
  types/gov/errors.go
  types/gov/params/gov_params.go
  types/gov/params/gov_params_test.go
  types/gov/params/util.go
  types/gov/proposal_halt.go
  types/gov/proposal_params.go
  types/gov/proposal_taxusage.go
  types/gov/proposal_upgrade.go
  types/gov/proposals.go
Labels: governance, refactoring

#862 R4R: Fix the test_cli and close gov cli test
  tests/cli/gov_test.go
  tests/cli/iparam_test.go
  tests/cli/utils.go
  tests/util.go
Labels: bug

#864 R4R: use address instead of bond height / intratxcounter for deduplication
  app/v0/export.go
  client/stake/utils.go
  modules/slashing/keeper_test.go
  modules/stake/genesis.go
  modules/stake/genesis_test.go
  modules/stake/handler.go
  modules/stake/keeper/delegation.go
  modules/stake/keeper/delegation_test.go
  modules/stake/keeper/keeper.go
  modules/stake/keeper/key.go
  modules/stake/keeper/key_test.go
  modules/stake/keeper/slash_test.go
  modules/stake/keeper/test_common.go
  modules/stake/keeper/validator.go
  modules/stake/keeper/validator_test.go
  modules/stake/querier/queryable_test.go
  modules/stake/stake.go
  modules/stake/types/genesis.go
  modules/stake/types/validator.go
Labels: bug, staking

#866 R4R: Removal of Mandatory Self-Delegation Reward
  modules/distribution/keeper/hooks.go
  modules/distribution/keeper/validator.go
  modules/distribution/keeper/validator_test.go
Labels: bug, staking

#867 R4R: lite bug fix and version update
  client/utils/rest.go
  lite/swagger-ui/swagger.yaml
  version/version.go
Labels: bug, client

#869 R4R: Setup different level min-deposit for different proposals
  lite/test_helpers.go
  modules/gov/genesis.go
  modules/gov/govparams_util.go
  modules/gov/handler.go
  modules/gov/keeper.go
  modules/gov/tally.go
  modules/gov/test_common.go
  types/gov/params/gov_params.go
  types/gov/params/gov_params_test.go
  types/gov/params/util.go
Labels: enhancement, governance

#870 R4R: Setup different level voting period for different proposals.
  modules/gov/genesis.go
  modules/gov/govparams_util.go
  modules/gov/keeper.go
  modules/gov/test_common.go
  types/gov/params/gov_params.go
  types/gov/params/gov_params_test.go
Labels: enhancement, governance

#872 R4R: Only burn the deposit when the proposal result is reject-veto
  modules/gov/handler.go
  modules/gov/tally.go
  types/gov/params/gov_params_test.go
Labels: enhancement, governance

#875 R4R: Fix cli test failure and fix bug in loosen token calculation when slashing
  modules/service/error.go
  modules/service/handler.go
  modules/service/keeper.go
  modules/service/keeper_keys.go
  modules/stake/keeper/slash.go
  modules/stake/simulation/invariants.go
  tests/cli/service_test.go
  tests/cli/stake_test.go
Labels: CI, token-economics

#871 R4R: remove deposit from required params
  client/gov/cli/sendtx.go
  client/gov/lcd/sendtx.go
Labels: client

#873 R4R: remove deposit from required params for v0.9
  client/gov/cli/sendtx.go
  client/gov/lcd/sendtx.go
Labels: client

#877 R4R: Add withdraw address into withdaw tag list
  modules/distribution/handler.go
  modules/distribution/tags/tags.go
  types/tags.go
Labels: enhancement

#880 R4R: add service slash and clean code
  modules/service/genesis.go
  modules/service/handler.go
  modules/service/keeper.go
  modules/service/keeper_keys.go
  modules/service/tags/tags.go
  tests/cli/service_test.go
Labels: enhancement

#882 R4R: fix unit test and tags sequence
  app/baseapp.go
  modules/service/keeper_test.go
Labels: bug

#879 R4R: Fix absence proof verification and add token stats query
  client/bank/cli/query.go
  client/bank/lcd/query.go
  client/bank/lcd/rest.go
  client/bank/utils.go
  client/context/context.go
  client/context/query.go
  cmd/iriscli/main.go
  lite/swagger-ui/swagger.yaml
  modules/auth/keeper.go
Labels: bug, token-economics

#876 R4R: Finish the new gov
  modules/gov/genesis.go
  modules/gov/govparams_util.go
  modules/gov/handler.go
  modules/gov/keeper.go
  modules/gov/keeper_keys.go
  modules/gov/queryable.go
  modules/gov/tally.go
  modules/params/errors.go
  types/gov/depositsvotes.go
  types/gov/errors.go
  types/gov/params/gov_params.go
  types/gov/proposals.go
Labels: enhancement, governance

#881 R4R: Implement block mint
  app/v0/genesis.go
  app/v0/protocol_v0.go
  modules/mint/abci_app.go
  modules/mint/minter.go
  modules/mint/minter_test.go
  modules/mint/params.go
  modules/mint/tags/tags.go
  types/gov/params/gov_params_test.go
Labels: token-economics

#883 R4R: Finish the refund and delete deposit
  modules/gov/handler.go
  modules/gov/keeper.go
  types/gov/params/gov_params_test.go
  types/gov/proposals.go
Labels: enhancement, governance

#885 R4R: Avoid to export account with no coin and improve export
  app/v0/export.go
Labels: enhancement, export

#859 IRISHUB-936 check genesis coin-type
  types/coin_type.go
Labels: genesis

#889 R4R: Improve gas price comment and replace decimal with int coins in distribution withdraw tags
  app/v0/protocol_v0.go
  modules/distribution/handler.go
  modules/distribution/keeper/delegation.go
  modules/distribution/keeper/validator.go
Labels: enhancement, token-economics

#890 R4R: Simplify the new gov
  app/v0/protocol_v0.go
  modules/gov/govparams_util.go
  modules/gov/handler.go
  modules/gov/keeper.go
  modules/gov/tally.go
  modules/gov/test_common.go
  types/gov/params/gov_params.go
Labels: enhancement, governance

#886 R4R: guardian refactor
  client/guardian/cli/flags.go
  client/guardian/cli/query.go
  client/guardian/cli/sendtx.go
  cmd/iriscli/main.go
  modules/guardian/error.go
  modules/guardian/genesis.go
  modules/guardian/handler.go
  modules/guardian/keeper.go
  modules/guardian/keeper_test.go
  modules/guardian/msgs.go
  modules/guardian/tags/tags.go
  modules/guardian/types.go
  modules/guardian/wire.go
  server/init/testnet.go
  tests/cli/guardian_test.go
  tests/cli/utils.go
Labels: guardian, refactoring

#894 R4R: Move prefix.go and protocol.go to /types
  Makefile
  app/protocol/keeper/types.go
  app/protocol/types.go
  app/v0/protocol_v0.go
  cmd/iris/main.go
  cmd/iriscli/main.go
  cmd/irislcd/main.go
  cmd/iristool/main.go
  modules/gov/execute.go
  modules/upgrade/genesis.go
  modules/upgrade/types.go
  tests/cli/utils.go
  tools/prometheus/server_test.go
  types/address.go
  types/prefix.go
  types/protocol.go
Labels: refactoring, types

#893 R4R: Update mint document to accommodate new mint implementation
  cmd/iris/main.go
  docs/cli-client/bank/token-stats.md
  docs/features/basic-concepts/inflation.md
  docs/features/mint.md
  docs/light-client/README.md
  docs/zh/cli-client/bank/README.md
  docs/zh/cli-client/bank/token-stats.md
  docs/zh/features/basic-concepts/inflation.md
  docs/zh/features/mint.md
  docs/zh/light-client/README.md
Labels: documentation, token-economics

#896 R4R: Make the upgrade tally threshold param be governability
  app/v0/protocol_v0.go
  client/gov/cli/query.go
  client/gov/lcd/query.go
  modules/params/errors.go
  modules/stake/types/params.go
  modules/upgrade/genesis.go
  modules/upgrade/params/upgrade_params.go
  modules/upgrade/tally.go
  modules/upgrade/upgradeparams_util.go
  types/gov/config_file.go
  types/gov/params/gov_params.go
Labels: enhancement, governance

#897 R4R: Fix the refund bug in deposit period
  modules/gov/handler.go
  modules/gov/keeper.go
Labels: bug

#898 R4R: FeePreprocessHandler return sdk.Error instead error
  app/baseapp.go
  modules/auth/fee.go
  types/handler.go
Labels: bug

#902 R4R: Refactor the service params
  app/v0/protocol_v0.go
  client/gov/cli/query.go
  client/gov/lcd/query.go
  modules/mock/app.go
  modules/params/errors.go
  modules/service/genesis.go
  modules/service/handler.go
  modules/service/keeper.go
  modules/service/params/service_params.go
  modules/service/params/service_params_test.go
  modules/service/params/util.go
  types/gov/config_file.go
Labels: governance, service

#906 R4R: Fix the panic to make test_cli pass
  types/gov/params/gov_params_test.go
Labels: testing

#907 R4R: fix monitor for v0.9
  tools/prometheus/consensus/metrics.go
Labels: bug, tools

#905 R4R: Add invariant checking config into iris.toml
  CHANGELOG.md
  app/app.go
  app/baseapp.go
  app/options.go
  app/v0/export.go
  app/v0/invariants.go
  app/v0/protocol_v0.go
  cmd/iris/main.go
  modules/stake/keeper/sdk_types.go
  modules/stake/simulation/invariants.go
  server/config/config.go
  server/config/config_test.go
  server/config/toml.go
  server/init/testnet.go
  server/util.go
  tests/cli/stake_test.go
  tools/debug/hack.go
Labels: configuration, enhancement

#908 R4R: fix monitor for tendermint v0.27.3
  client/guardian/cli/sendtx.go
  tests/cli/irismon_test.go
  tools/prometheus/consensus/metrics.go
Labels: bug, tools

#910 R4R: Fix a bug in stake genesis initialization
  app/v0/protocol_v0.go
  lite/swagger-ui/swagger.yaml
  modules/auth/genesis.go
  modules/distribution/genesis.go
  modules/mock/app.go
  modules/stake/genesis.go
Labels: bug, staking

#912 R4R: Fix issue that Gov initialization fail to reset Proposal-ID to 1
  modules/gov/genesis.go
  modules/gov/test_common.go
Labels: enhancement, governance

#888 IRISHUB-973:edit docs
  docs/cli-client/gov/submit-proposal.md
  docs/cli-client/service/bind.md
  docs/cli-client/stake/delegations-to.md
  docs/cli-client/upgrade/README.md
  docs/cli-client/upgrade/query-signals.md
  docs/features/basic-concepts/bech32-prefix.md
  docs/features/basic-concepts/fee.md
  docs/features/basic-concepts/genesis-file.md
  docs/features/basic-concepts/gov-params.md
  docs/features/distribution.md
  docs/features/governance.md
  docs/features/service.md
  docs/features/upgrade.md
  docs/get-started/Install-the-Software.md
  docs/get-started/Join-the-Testnet.md
  docs/get-started/Validator-Node.md
  docs/software/monitor.md
  docs/zh/cli-client/gov/submit-proposal.md
  docs/zh/cli-client/service/bind.md
  docs/zh/cli-client/stake/delegations-to.md
  docs/zh/cli-client/upgrade/README.md
  docs/zh/cli-client/upgrade/query-signals.md
  docs/zh/features/basic-concepts/bech32-prefix.md
  docs/zh/features/basic-concepts/fee.md
  docs/zh/features/basic-concepts/genesis-file.md
  docs/zh/features/basic-concepts/gov-params.md
  docs/zh/features/distribution.md
  docs/zh/features/governance.md
  docs/zh/features/service.md
  docs/zh/features/stake.md
  docs/zh/features/test.proto
  docs/zh/features/upgrade.md
  docs/zh/get-started/Full-Node.md
  docs/zh/get-started/Install-the-Software.md
  docs/zh/get-started/Join-the-Testnet.md
  docs/zh/get-started/README.md
  docs/zh/get-started/Validator-Node.md
  docs/zh/software/sentry.md
Labels: documentation

#921 R4R: Move SetProtocolEngine() to baseapp
  app/app.go
  app/baseapp.go
  app/options.go
Labels: refactoring

#915 R4R: Move the types/gov to modules/gov and delete the parameterConfigFile
  app/app.go
  app/v0/protocol_v0.go
  client/gov/cli/query.go
  client/gov/cli/sendtx.go
  client/gov/lcd/query.go
  client/gov/lcd/rest.go
  client/gov/lcd/sendtx.go
  client/gov/utils.go
  cmd/iriscli/main.go
  modules/auth/account.go
  modules/auth/codec.go
  modules/bank/codec.go
  modules/distribution/types/codec.go
  modules/gov/codec.go
  modules/gov/depositsvotes.go
  modules/gov/errors.go
  modules/gov/execute.go
  modules/gov/genesis.go
  modules/gov/govparams_util.go
  modules/gov/handler.go
  modules/gov/keeper.go
  modules/gov/keeper_keys.go
  modules/gov/msgs.go
  modules/gov/params/gov_params.go
  modules/gov/params/gov_params_test.go
  modules/gov/proposal_halt.go
  modules/gov/proposal_params.go
  modules/gov/proposal_taxusage.go
  modules/gov/proposal_upgrade.go
  modules/gov/proposals.go
  modules/gov/queryable.go
  modules/gov/simulation/msgs.go
  modules/gov/simulation/sim_test.go
  modules/gov/tally.go
  modules/gov/test_common.go
  modules/guardian/wire.go
  modules/mock/app.go
  modules/record/codec.go
  modules/service/wire.go
  modules/slashing/codec.go
  modules/stake/types/codec.go
  tests/cli/gov_test.go
  tests/cli/iparam_test.go
  tests/cli/utils.go
  tools/prometheus/governance/metrics.go
  types/gov/codec.go
  types/gov/config_file.go
  types/gov/proposal_halt.go
Labels: governance, refactoring

#887 IRISHUB-973:文档优化
  docs/cli-client/service/bind.md
  docs/cli-client/stake/delegations-to.md
  docs/features/basic-concepts/bech32-prefix.md
  docs/features/basic-concepts/fee.md
  docs/features/basic-concepts/genesis-file.md
  docs/features/basic-concepts/gov-params.md
  docs/features/distribution.md
  docs/features/service.md
  docs/features/upgrade.md
  docs/get-started/Install-the-Software.md
  docs/get-started/Join-the-Testnet.md
  docs/get-started/Validator-Node.md
  docs/software/monitor.md
  docs/zh/cli-client/service/bind.md
  docs/zh/cli-client/stake/delegations-to.md
  docs/zh/features/basic-concepts/bech32-prefix.md
  docs/zh/features/basic-concepts/fee.md
  docs/zh/features/basic-concepts/genesis-file.md
  docs/zh/features/basic-concepts/gov-params.md
  docs/zh/features/distribution.md
  docs/zh/features/service.md
  docs/zh/features/stake.md
  docs/zh/features/test.proto
  docs/zh/features/upgrade.md
  docs/zh/get-started/Full-Node.md
  docs/zh/get-started/Install-the-Software.md
  docs/zh/get-started/Join-the-Testnet.md
  docs/zh/get-started/README.md
  docs/zh/get-started/Validator-Node.md
  docs/zh/software/sentry.md
Labels: documentation

#920 R4R: If a validator is jailed, distribute no reward to it
  modules/distribution/keeper/allocation.go
  tests/cli/guardian_test.go
  tests/cli/stake_test.go
  tests/cli/utils.go
Labels: bug, staking

#935 R4R: Add service export
  app/v0/export.go
  modules/guardian/msgs.go
  modules/service/genesis.go
Labels: service

#934 R4R: Refactor the parameterChange, mint as the example
  app/v0/protocol_v0.go
  client/distribution/cli/sendtx.go
  client/gov/cli/query.go
  client/gov/cli/sendtx.go
  client/gov/lcd/sendtx.go
  lite/swagger-ui/swagger-ui-bundle.js.map
  modules/gov/execute.go
  modules/gov/handler.go
  modules/gov/keeper.go
  modules/gov/msgs.go
  modules/gov/proposal_params.go
  modules/gov/queryable.go
  modules/gov/simulation/msgs.go
  modules/gov/simulation/sim_test.go
  modules/gov/test_common.go
  modules/mint/abci_app.go
  modules/mint/genesis.go
  modules/mint/keeper.go
  modules/mint/params.go
  modules/params/errors.go
  modules/params/helper.go
  modules/params/subspace/pair.go
  modules/params/subspace/table_test.go
  modules/slashing/params.go
  modules/stake/types/params.go
  tests/cli/iparam_test.go
Labels: governance, refactoring

#939 R4R: Remove the record module
  app/app.go
  app/v0/protocol_v0.go
  client/record/cli/download.go
  client/record/cli/flags.go
  client/record/cli/query.go
  client/record/cli/sendtx.go
  client/record/lcd/flag.go
  client/record/lcd/query.go
  client/record/lcd/rest.go
  client/record/lcd/sendtx.go
  client/record/utils.go
  cmd/iriscli/main.go
  docs/cli-client/record/README.md
  docs/cli-client/record/download.md
  docs/cli-client/record/query.md
  docs/cli-client/record/submit.md
  docs/features/record.md
  docs/zh/cli-client/record/README.md
  docs/zh/cli-client/record/download.md
  docs/zh/cli-client/record/query.md
  docs/zh/cli-client/record/submit.md
  docs/zh/features/record.md
  lite/lcd.go
  modules/record/codec.go
  modules/record/errors.go
  modules/record/handler.go
  modules/record/keeper.go
  modules/record/keeper_test.go
  modules/record/msgs.go
  modules/record/msgs_test.go
  modules/record/tags/tags.go
  modules/record/test_common.go
  tools/debug/hack.go
Labels: record

#944 Set invariants check level to 'error' for Prod env
  Makefile
  scripts/setProdEnv.sh
Labels: configuration

#949 R4R: refactor slashing params
  app/v0/protocol_v0.go
  client/gov/cli/query.go
  modules/mint/genesis.go
  modules/params/errors.go
  modules/slashing/genesis.go
  modules/slashing/handler_test.go
  modules/slashing/hooks_test.go
  modules/slashing/keeper_test.go
  modules/slashing/params.go
  modules/slashing/signing_info_test.go
  modules/slashing/slashing_period_test.go
  modules/slashing/tick_test.go
  types/duration.go
Labels: params, refactoring

#951 R4R: Refactor the gov params
  app/v0/protocol_v0.go
  client/gov/cli/query.go
  modules/gov/codec.go
  modules/gov/errors.go
  modules/gov/genesis.go
  modules/gov/govparams_util.go
  modules/gov/handler.go
  modules/gov/keeper.go
  modules/gov/keeper_keys.go
  modules/gov/msgs.go
  modules/gov/params.go
  modules/gov/params/gov_params.go
  modules/gov/params/gov_params_test.go
  modules/gov/proposals.go
  modules/gov/simulation/sim_test.go
  modules/gov/tally.go
  modules/gov/test_common.go
  modules/mock/app.go
  modules/params/errors.go
  types/duration.go
Labels: params, refactoring

#948 R4R: check destination address is a trustee when TaxUsage proposal execute
  client/guardian/cli/sendtx.go
  modules/gov/execute.go
Labels: guardian

#954 R4R: Refactor service params
  app/v0/export.go
  app/v0/genesis.go
  app/v0/protocol_v0.go
  client/gov/cli/query.go
  modules/arbitration/genesis.go
  modules/arbitration/params/arbitration_params.go
  modules/arbitration/params/arbitration_params_test.go
  modules/arbitration/params/util.go
  modules/mock/app.go
  modules/params/errors.go
  modules/service/genesis.go
  modules/service/handler.go
  modules/service/keeper.go
  modules/service/params.go
  modules/service/params/service_params.go
  modules/service/params/service_params_test.go
  modules/service/params/util.go
  modules/service/test_common.go
  tests/cli/utils.go
Labels: params, refactoring, service

#958 R4R: Clean up global constants and their usage
  app/app.go
  app/v0/genesis.go
  app/v0/protocol_v0.go
  client/context/query.go
  client/distribution/utils.go
  client/stake/cli/sendtx.go
  client/utils/utils.go
  cmd/iris/main.go
  cmd/iriscli/main.go
  cmd/irislcd/main.go
  cmd/iristool/main.go
  modules/gov/params.go
  modules/gov/test_common.go
  modules/mint/minter.go
  modules/mint/minter_test.go
  modules/mock/app.go
  modules/stake/types/params.go
  server/init/gentx.go
  server/init/testnet.go
  tests/cli/bank_test.go
  tests/cli/distribution_test.go
  tests/cli/gov_test.go
  tests/cli/guardian_test.go
  tests/cli/iparam_test.go
  tests/cli/service_test.go
  tests/cli/stake_test.go
  tests/cli/utils.go
  tools/prometheus/server_test.go
  types/address_test.go
  types/config.go
  types/prefix.go
Labels: configuration, refactoring
