Repository irisnet/irishub, pull requests merged in 2019-02, with the labels that each got.

#1212 R4R: Fix the metrics bugs and docs
  client/flags.go
  docs/software/monitor.md
  docs/zh/features/basic-concepts/fee.md
  docs/zh/software/cli-client.md
  docs/zh/software/monitor.md
  modules/stake/keeper/keeper.go
  modules/stake/keeper/slash.go
  modules/stake/keeper/val_state_change.go
Labels: documentation, metric

#1216 R4R: Fix cli test
  tests/cli/service_test.go
  tests/cli/stake_test.go
Labels: test

#1217 R4R: Fix cli test for v0.12
  tests/cli/service_test.go
  tests/cli/stake_test.go
Labels: test

#1219 edit docs for v0.12
  docs/get-started/Download-Rainbow.md
  docs/get-started/Full-Node.md
  docs/get-started/Install-the-Software.md
  docs/get-started/Join-the-Testnet.md
  docs/get-started/README.md
  docs/get-started/Validator-Node.md
  docs/zh/get-started/Download-Rainbow.md
  docs/zh/get-started/Full-Node.md
  docs/zh/get-started/Install-the-Software.md
  docs/zh/get-started/Join-the-Testnet.md
  docs/zh/get-started/README.md
  docs/zh/get-started/Validator-Node.md
Labels: documentation

#1222 edit docs on develop
  docs/get-started/Download-Rainbow.md
  docs/get-started/Full-Node.md
  docs/get-started/Install-the-Software.md
  docs/get-started/Join-the-Testnet.md
  docs/get-started/README.md
  docs/get-started/Validator-Node.md
  docs/zh/get-started/Download-Rainbow.md
  docs/zh/get-started/Full-Node.md
  docs/zh/get-started/Install-the-Software.md
  docs/zh/get-started/Join-the-Testnet.md
  docs/zh/get-started/README.md
  docs/zh/get-started/Validator-Node.md
Labels: documentation

#1237 Edit Install Docs on Release0.12
  Makefile
  docs/get-started/Install-the-Software.md
  docs/zh/get-started/Install-the-Software.md
Labels: documentation

#1238 R4R: Update install doc for v0.12
  Makefile
  docs/get-started/Install-the-Software.md
  docs/zh/get-started/Install-the-Software.md
Labels: documentation

#1239 R4R: release version v0.12.1
  CHANGELOG.md
  version/version.go
Labels: release

#1233 R4R: change invariant level for mainnet
  scripts/setProdEnv.sh
Labels: invariant

#1236 R4R: Upgrade tendermint dependency
  Gopkg.lock
  Gopkg.toml
Labels: tendermint

#1240 R4R: update docs
  docs/get-started/Install-the-Software.md
  docs/zh/get-started/Install-the-Software.md
Labels: documentation

#1241 R4R: Release version v0.12.1
  CHANGELOG.md
  Gopkg.lock
  Gopkg.toml
  Makefile
  docs/get-started/Install-the-Software.md
  docs/zh/get-started/Install-the-Software.md
  scripts/setProdEnv.sh
  version/version.go
Labels: release

#1246 Edit Docs on Release0.12
  docs/.vuepress/config.js
  docs/get-started/Full-Node.md
  docs/get-started/Join-the-Mainnet.md
  docs/get-started/Join-the-Testnet.md
  docs/get-started/README.md
  docs/get-started/Validator-Node.md
  docs/software/How-to-install-Irishub.md
  docs/software/node.md
  docs/zh/get-started/Full-Node.md
  docs/zh/get-started/Join-the-Mainnet.md
  docs/zh/get-started/Join-the-Testnet.md
  docs/zh/get-started/README.md
  docs/zh/get-started/Validator-Node.md
  docs/zh/software/How-to-install-irishub.md
  docs/zh/software/node.md
Labels: documentation

#1247 R4R: Fix the docs issue
  docs/software/cli-client.md
  docs/zh/software/cli-client.md
Labels: documentation

#1251 R4R: Fix wrong withdraw address
  modules/distribution/keeper/validator.go
Labels: bug, distr

#1252 R4R: Fix wrong withdraw address
  modules/distribution/keeper/validator.go
Labels: bug, distr

#1249 R4R: Fix gas simulate issue
  client/flags.go
Labels: bug, client, simulation

#1261 edit chain-id on release0.12
  docs/cli-client/bank/account.md
  docs/cli-client/bank/broadcast.md
  docs/cli-client/bank/burn.md
  docs/cli-client/bank/send.md
  docs/cli-client/bank/sign.md
  docs/cli-client/gov/query-deposit.md
  docs/cli-client/gov/query-deposits.md
  docs/cli-client/service/binding.md
  docs/cli-client/service/bindings.md
  docs/cli-client/service/definition.md
  docs/cli-client/service/disable.md
  docs/cli-client/service/enable.md
  docs/cli-client/service/refund-deposit.md
  docs/cli-client/service/refund-fees.md
  docs/cli-client/service/requests.md
  docs/cli-client/service/respond.md
  docs/cli-client/service/response.md
  docs/cli-client/service/withdraw-fees.md
  docs/cli-client/stake/delegate.md
  docs/cli-client/stake/edit-validator.md
  docs/cli-client/stake/unbond.md
  docs/cli-client/tendermint/block.md
  docs/cli-client/tendermint/tx.md
  docs/cli-client/tendermint/txs.md
  docs/cli-client/tendermint/validator-set.md
Labels: documentation

#1256 R4R: Update docs of version v0.12.1
  client/flags.go
  docs/.vuepress/config.js
  docs/cli-client/bank/account.md
  docs/cli-client/bank/broadcast.md
  docs/cli-client/bank/burn.md
  docs/cli-client/bank/send.md
  docs/cli-client/bank/sign.md
  docs/cli-client/gov/query-deposit.md
  docs/cli-client/gov/query-deposits.md
  docs/cli-client/service/binding.md
  docs/cli-client/service/bindings.md
  docs/cli-client/service/definition.md
  docs/cli-client/service/disable.md
  docs/cli-client/service/enable.md
  docs/cli-client/service/refund-deposit.md
  docs/cli-client/service/refund-fees.md
  docs/cli-client/service/requests.md
  docs/cli-client/service/respond.md
  docs/cli-client/service/response.md
  docs/cli-client/service/withdraw-fees.md
  docs/cli-client/stake/delegate.md
  docs/cli-client/stake/edit-validator.md
  docs/cli-client/stake/unbond.md
  docs/cli-client/tendermint/block.md
  docs/cli-client/tendermint/tx.md
  docs/cli-client/tendermint/txs.md
  docs/cli-client/tendermint/validator-set.md
  docs/get-started/Full-Node.md
  docs/get-started/Join-the-Mainnet.md
  docs/get-started/Join-the-Testnet.md
  docs/get-started/README.md
  docs/get-started/Validator-Node.md
  docs/software/How-to-install-Irishub.md
  docs/software/cli-client.md
  docs/software/node.md
  docs/zh/get-started/Full-Node.md
  docs/zh/get-started/Join-the-Mainnet.md
  docs/zh/get-started/Join-the-Testnet.md
  docs/zh/get-started/README.md
  docs/zh/get-started/Validator-Node.md
  docs/zh/software/How-to-install-irishub.md
  docs/zh/software/cli-client.md
  docs/zh/software/node.md
  modules/distribution/keeper/validator.go
Labels: documentation

#1259 R4R: Configure the default build environment as mainnet
  Makefile
  scripts/setTestEnv.sh
Labels: build

#1255 R4R: Set max commission rate and max commission change rate to 100%
  client/stake/cli/flags.go
  client/stake/cli/sendtx.go
  docs/cli-client/stake/create-validator.md
  docs/features/stake.md
  docs/get-started/Validator-Node.md
  docs/zh/cli-client/stake/create-validator.md
  docs/zh/features/stake.md
  docs/zh/get-started/Validator-Node.md
  modules/stake/handler.go
  server/init/gentx.go
  server/init/testnet.go
  tests/cli/stake_test.go
Labels: stake

#1264 R4R: Fix service parameter change error msg for testnet
  modules/service/params.go
Labels: bug

#1267 R4R: fix docs issue
  docs/features/basic-concepts/fee.md
  docs/zh/features/basic-concepts/fee.md
Labels: documentation

#1268 R4R: implement coin flow record
  app/app.go
  app/baseapp.go
  app/options.go
  app/v0/protocol_v0.go
  cmd/iris/main.go
  modules/bank/handler.go
  modules/bank/keeper.go
  modules/distribution/keeper/allocation.go
  modules/distribution/keeper/delegation.go
  modules/distribution/keeper/hooks.go
  modules/distribution/keeper/validator.go
  modules/gov/handler.go
  modules/gov/keeper.go
  modules/service/keeper.go
  modules/slashing/tick.go
  modules/stake/handler.go
  modules/stake/keeper/delegation.go
  server/config/config.go
  server/config/toml.go
  tools/debug/hack.go
  types/context.go
  types/contexttags.go
Labels: book-keeping

#1269 R4R: Add APIs in LCD
  client/tendermint/rpc/block.go
  client/tendermint/rpc/blockresult.go
  client/tendermint/rpc/rest.go
  client/tendermint/rpc/validatorset.go
  client/tendermint/tx/querytx.go
  client/tendermint/tx/searchtx.go
  client/tendermint/utils.go
  cmd/iriscli/main.go
  lite/swagger-ui/swagger.yaml
Labels: client, coin-flow

#1270 edit validator faq on release 0.12
  docs/resources/validator-faq.md
  docs/zh/resources/validator-faq.md
Labels: documentation

#1271 R4R: Fix compile error
  client/tendermint/tx/querytx.go
Labels: client, coin-flow

#1273 R4R: Fix simulated gas too low issue
  app/baseapp.go
  app/helpers.go
Labels: bug

#1279 Fix error in validator-faq.md
  docs/zh/resources/validator-faq.md
Labels: documentation

#1281 display correct validator consensus pubkey
  client/stake/utils.go
Labels: bug, client

#1284 Edit Validator FAQ
  Makefile
  docs/resources/validator-faq.md
  docs/zh/resources/validator-faq.md
Labels: documentation

#1283 R4R: fix unit test failure and change prefix for sign-info query
  app/baseapp.go
  client/slashing/cli/query.go
  client/slashing/lcd/query.go
  client/tendermint/rpc/validatorset.go
  docs/cli-client/stake/unjail.md
  docs/cli-client/stake/validator.md
  docs/cli-client/stake/validators.md
  docs/cli-client/tendermint/validator-set.md
  docs/features/stake.md
  docs/get-started/Validator-Node.md
  docs/zh/cli-client/stake/unjail.md
  docs/zh/cli-client/stake/validator.md
  docs/zh/cli-client/stake/validators.md
  docs/zh/cli-client/tendermint/validator-set.md
  docs/zh/features/stake.md
  docs/zh/get-started/Validator-Node.md
  types/context.go
Labels: bug, client, test

#1286 R4R: Add desc coin flow
  modules/bank/handler.go
  modules/bank/keeper.go
  modules/distribution/keeper/allocation.go
  modules/distribution/keeper/delegation.go
  modules/distribution/keeper/hooks.go
  modules/distribution/keeper/validator.go
  modules/gov/keeper.go
  modules/stake/keeper/delegation.go
  modules/stake/types/delegation.go
  types/contexttags.go
Labels: coin-flow

#1288 R4R: Remove duplicated coin flow record
  modules/distribution/keeper/delegation.go
Labels: bug, coin-flow

#1287 R4R: Make KMS available
  Gopkg.lock
  Gopkg.toml
  Makefile
  crypto/ledger.go
  crypto/ledger_secp256k1.go
Labels: kms

#1292 R4R: Support zero slash fraction for downtime and censorship
  modules/gov/params.go
  modules/slashing/params.go
Labels: param

#1290 R4R: Add coin flow record for gov deposit burn
  modules/gov/keeper.go
  types/contexttags.go
Labels: coin-flow, governance

#1294 R4R: Fix slashing param names and some gov/stake/slashing default param values
  modules/gov/params.go
  modules/slashing/keeper.go
  modules/slashing/keeper_test.go
  modules/slashing/params.go
  modules/stake/types/params.go
  types/duration.go
Labels: param

#1293 R4R: Use the NewCoin function instead of build Coin struct
  CHANGELOG.md
  mock/app.go
  modules/auth/feeauth.go
  modules/service/handler.go
  modules/service/keeper.go
  modules/slashing/keeper_test.go
  modules/stake/keeper/slash.go
  types/coin.go
Labels: enhancement, type

#1295 R4R: Relax max allowed voting period to 1 week
  modules/gov/params.go
Labels: governance, param

#1297 R4R: Allow non-voting penalty to be zero
  modules/gov/params.go
Labels: governance, param

#1299 R4R: Fix bug for iriscli delete ledger keys
  client/keys/cli/delete.go
  client/keys/lcd/delete.go
  crypto/keys/keybase.go
  crypto/keys/types.go
  docs/cli-client/keys/delete.md
  docs/zh/cli-client/keys/delete.md
Labels: client, key

#1300 R4R: Set reasonable defaults for slashing params
  modules/slashing/params.go
Labels: param, slash

#1291 R4R: Docs for KMS and Ledger User App
  docs/.vuepress/config.js
  docs/get-started/Join-the-Mainnet.md
  docs/software/kms/kms.md
  docs/software/kms/kms_cpu.md
  docs/software/kms/kms_ledger.md
  docs/software/kms/kms_yubihsm.md
  docs/software/kms/ledger_1.jpg
  docs/software/kms/ledger_2.jpg
  docs/software/ledger.md
  docs/zh/get-started/Join-the-Mainnet.md
  docs/zh/software/kms/kms.md
  docs/zh/software/kms/kms_cpu.md
  docs/zh/software/kms/kms_ledger.md
  docs/zh/software/kms/kms_yubihsm.md
  docs/zh/software/kms/ledger_1.jpg
  docs/zh/software/kms/ledger_2.jpg
  docs/zh/software/ledger.md
Labels: documentation, kms, ledger

#1303 R4R: Validate and fix the docs
  docs/software/kms/kms.md
  docs/software/ledger.md
  docs/zh/software/kms/kms.md
  docs/zh/software/ledger.md
Labels: documentation, ledger

#1309 R4R: Correct document for compile
  docs/get-started/Install-the-Software.md
  docs/zh/get-started/Install-the-Software.md
Labels: documentation

#1310 R4R: release 0.12.2
  CHANGELOG.md
  docs/get-started/Install-the-Software.md
  docs/software/How-to-install-Irishub.md
  docs/zh/get-started/Install-the-Software.md
  docs/zh/software/How-to-install-irishub.md
  version/version.go
Labels: release

#1311 R4R: Release version v0.12.2
  CHANGELOG.md
  docs/get-started/Install-the-Software.md
  docs/resources/validator-faq.md
  docs/software/How-to-install-Irishub.md
  docs/zh/get-started/Install-the-Software.md
  docs/zh/resources/validator-faq.md
  docs/zh/software/How-to-install-irishub.md
  version/version.go
Labels: release

#1312 R4R: enable cgo in build_linux
  Makefile
Labels: build

#1316 R4R： fix dockerfile issue
  Dockerfile
  Dockerfile-testnet
  docs/software/export.md
Labels: build

#1317 R4R: Fix build in alpine
  CHANGELOG.md
  Dockerfile
Labels: build

#1323 R4R: update changelog for release v0.12.3
  CHANGELOG.md
Labels: release

#1324 R4R: Improve docs
  docs/software/kms/kms_yubihsm.md
  docs/zh/features/basic-concepts/bech32-prefix.md
  docs/zh/software/kms/kms_yubihsm.md
Labels: documentation

#1325 Edit readme
  README.md
  docs/software/sentry.md
Labels: documentation
