Repository irisnet/irishub, pull requests merged in 2019-03, with the labels that each got.

#1326 Update sentry.md
  docs/software/sentry.md
  docs/zh/software/sentry.md
Labels: documentation

#1328 Edit get-started
  docs/get-started/Full-Node.md
  docs/zh/get-started/Full-Node.md
Labels: documentation

#1329 Improve error message for insufficient balance
  modules/auth/ante.go
Labels: client

#1327 R4R: Improve docs
  docs/cli-client/gov/README.md
  docs/zh/cli-client/gov/README.md
  docs/zh/software/ledger.md
Labels: documentation

#1338 tar can't unzip zip,need unzip command
  docs/zh/get-started/Install-the-Software.md
Labels: documentation

#1340 R4R: Fix unexpect coin flow if tx is out of gas
  app/baseapp.go
Labels: bug, coin-flow

#1339 R4R: Add pagination params for lcd validators query
  client/stake/lcd/query.go
  client/stake/lcd/utils.go
  lite/swagger-ui/swagger.yaml
  modules/stake/handler_test.go
  modules/stake/keeper/validator.go
  modules/stake/keeper/validator_test.go
  modules/stake/querier/queryable.go
  modules/stake/querier/queryable_test.go
  types/errors.go
  types/queryable.go
Labels: client

#1337 R4R：Modifying Document Errors
  docs/cli-client/gov/README.md
  docs/cli-client/stake/parameters.md
  docs/cli-client/stake/unbonding-delegations-from.md
  docs/features/guardian.md
  docs/features/service.md
  docs/features/stake.md
  docs/light-client/README.md
  docs/software/cli-client.md
  docs/software/sentry.md
  docs/software/tool.md
  docs/zh/cli-client/distribution/delegator-distr-info.md
  docs/zh/cli-client/gov/README.md
  docs/zh/cli-client/stake/parameters.md
  docs/zh/cli-client/stake/unbonding-delegations-from.md
  docs/zh/features/basic-concepts/fee.md
  docs/zh/features/distribution.md
  docs/zh/features/guardian.md
  docs/zh/features/service.md
  docs/zh/features/stake.md
  docs/zh/get-started/Install-the-Software.md
  docs/zh/get-started/Validator-Node.md
  docs/zh/light-client/README.md
  docs/zh/software/cli-client.md
  docs/zh/software/sentry.md
  docs/zh/software/tool.md
Labels: documentation

#1341 R4R: Check the validator existence and validator status before getting its pubkey
  modules/slashing/keeper.go
Labels: bug, slash

#1342 R4R: remove unused msg in the bank module
  modules/bank/codec.go
  modules/bank/handler.go
  modules/bank/msgs.go
  modules/bank/msgs_test.go
  modules/stake/keeper/test_common.go
  version/version.go
Labels: bank

#1343 R4R: Sync the changes of docs from master
  README.md
  docs/cli-client/gov/README.md
  docs/cli-client/stake/parameters.md
  docs/cli-client/stake/unbonding-delegations-from.md
  docs/features/guardian.md
  docs/features/service.md
  docs/features/stake.md
  docs/get-started/Full-Node.md
  docs/light-client/README.md
  docs/software/cli-client.md
  docs/software/kms/kms_yubihsm.md
  docs/software/sentry.md
  docs/software/tool.md
  docs/zh/cli-client/distribution/delegator-distr-info.md
  docs/zh/cli-client/gov/README.md
  docs/zh/cli-client/stake/parameters.md
  docs/zh/cli-client/stake/unbonding-delegations-from.md
  docs/zh/features/basic-concepts/bech32-prefix.md
  docs/zh/features/basic-concepts/fee.md
  docs/zh/features/distribution.md
  docs/zh/features/guardian.md
  docs/zh/features/service.md
  docs/zh/features/stake.md
  docs/zh/get-started/Full-Node.md
  docs/zh/get-started/Install-the-Software.md
  docs/zh/get-started/Validator-Node.md
  docs/zh/light-client/README.md
  docs/zh/software/cli-client.md
  docs/zh/software/kms/kms_yubihsm.md
  docs/zh/software/ledger.md
  docs/zh/software/sentry.md
  docs/zh/software/tool.md
Labels: documentation

#1345 R4R: Fix document link
  docs/software/kms/kms_yubihsm.md
  docs/zh/get-started/Join-the-Mainnet.md
  docs/zh/software/kms/kms_yubihsm.md
Labels: documentation

#1344 R4R: Add metrics initialization
  app/app.go
  app/protocol/types.go
  app/v0/protocol_v0.go
  modules/distribution/keeper/allocation.go
  modules/service/keeper.go
  modules/stake/keeper/keeper.go
  modules/stake/keeper/slash.go
  modules/stake/keeper/val_state_change.go
  modules/stake/keeper/validator.go
  modules/stake/types/validator.go
  modules/upgrade/handler.go
  modules/upgrade/metrics.go
  types/coin_type.go
Labels: bug, metric

#1348 R4R: Basic introduce of IRISnet key
  docs/.vuepress/config.js
  docs/features/basic-concepts/key.md
  docs/software/ledger.md
  docs/zh/features/basic-concepts/key.md
  docs/zh/software/ledger.md
Labels: documentation

#1354 R4R: Fix bug for validator query and metrics
  client/stake/utils.go
  modules/distribution/keeper/allocation.go
  modules/distribution/keeper/metrics.go
Labels: bug, client, metric

#1351 R4R: update txs search example && release version 0.13.0-rc0
  CHANGELOG.md
  Gopkg.lock
  Gopkg.toml
  client/tendermint/tx/searchtx.go
  docs/cli-client/tendermint/txs.md
  docs/zh/cli-client/tendermint/txs.md
  version/version.go
Labels: client, documentation, release

#1357 R4R: Fix wrong docs
  docs/get-started/Validator-Node.md
  docs/zh/get-started/Validator-Node.md
Labels: documentation

#1356 R4R: release version v0.13.0-rc0
  CHANGELOG.md
  Gopkg.lock
  Gopkg.toml
  app/app.go
  app/baseapp.go
  app/protocol/types.go
  app/v0/protocol_v0.go
  client/stake/lcd/query.go
  client/stake/lcd/utils.go
  client/tendermint/tx/searchtx.go
  docs/cli-client/tendermint/txs.md
  docs/zh/cli-client/tendermint/txs.md
  lite/swagger-ui/swagger.yaml
  modules/auth/ante.go
  modules/distribution/keeper/allocation.go
  modules/service/keeper.go
  modules/service/params.go
  modules/slashing/keeper.go
  modules/stake/handler_test.go
  modules/stake/keeper/keeper.go
  modules/stake/keeper/slash.go
  modules/stake/keeper/val_state_change.go
  modules/stake/keeper/validator.go
  modules/stake/keeper/validator_test.go
  modules/stake/querier/queryable.go
  modules/stake/querier/queryable_test.go
  modules/stake/types/validator.go
  modules/upgrade/handler.go
  modules/upgrade/metrics.go
  types/coin_type.go
  types/errors.go
  types/queryable.go
  version/version.go
Labels: release

#1358 R4R: Fix wrong docs
  docs/get-started/Validator-Node.md
  docs/zh/get-started/Validator-Node.md
Labels: documentation

#1359 R4R: Fix client issue and update docs
  client/stake/utils.go
  docs/.vuepress/config.js
  docs/features/basic-concepts/key.md
  docs/software/kms/kms_yubihsm.md
  docs/software/ledger.md
  docs/zh/features/basic-concepts/key.md
  docs/zh/get-started/Join-the-Mainnet.md
  docs/zh/software/kms/kms_yubihsm.md
  docs/zh/software/ledger.md
  modules/distribution/keeper/allocation.go
  modules/distribution/keeper/metrics.go
Labels: bug, documentation

#1360 R4R: Add rewards query
  client/distribution/cli/query.go
  client/distribution/lcd/query.go
  client/distribution/lcd/rest.go
  client/distribution/utils.go
  cmd/iriscli/main.go
  docs/cli-client/distribution/README.md
  docs/cli-client/distribution/rewards.md
  docs/zh/cli-client/distribution/README.md
  docs/zh/cli-client/distribution/rewards.md
  lite/swagger-ui/swagger.yaml
Labels: client, distr

#1362 R4R: Fix alpine build for testnet
  Dockerfile-testnet
Labels: build

#1364 R4R: Fix rewards compute
  client/distribution/utils.go
Labels: bug, client, distr

#1377 R4R: Add querier for account query
  app/v0/protocol_v0.go
  client/bank/lcd/query.go
  client/context/query.go
  modules/auth/account_test.go
  modules/auth/ante_test.go
  modules/auth/keeper.go
  modules/auth/querier.go
  modules/auth/querier_test.go
  modules/auth/test_utils.go
Labels: bank, client, refactoring

#1380 R4R: Fix the Introduction section of docs
  docs/introduction/README.md
  docs/zh/introduction/README.md
Labels: documentation
