Repository irisnet/irishub, pull requests merged in 2019-11, with the labels that each got.

#2051 R4R: Refactor HTLC
  app/v1/auth/keeper.go
  app/v2/genesis.go
  app/v2/htlc/genesis_test.go
  app/v2/htlc/handler.go
  app/v2/htlc/internal/keeper/keeper.go
  app/v2/htlc/internal/keeper/keeper_test.go
  app/v2/htlc/internal/types/htlc.go
  app/v2/htlc/internal/types/msgs.go
  app/v2/htlc/internal/types/msgs_test.go
  client/htlc/cli/flags.go
  client/htlc/cli/sendtx.go
  client/htlc/lcd/senttx.go
  docs/cli-client/htlc.md
  docs/features/htlc.md
  docs/zh/cli-client/htlc.md
  docs/zh/features/htlc.md
  go.mod
  go.sum
  lite/swagger-ui/swagger.yaml
  tests/cli/htlc_test.go
Labels: HTLC, client

#2052 R4R: Uniform fee and flag format
  client/bank/cli/sendtx.go
  client/distribution/cli/sendtx.go
  client/gov/cli/sendtx.go
  client/guardian/cli/sendtx.go
  client/service/cli/sendtx.go
  client/slashing/cli/sendtx.go
  client/stake/cli/sendtx.go
  docs/cli-client/asset.md
  docs/zh/cli-client/asset.md
  tests/cli/distribution_test.go
  tests/cli/service_test.go
Labels: CLI, documentation

#2053 R4R: Panic with string type
  types/coin.go
Labels: client

#2057 R4R: Add secret check in CLI
  app/v2/htlc/alias.go
  client/htlc/cli/sendtx.go
Labels: CLI, HTLC, bug

#2058 R4R: Update changelog
  CHANGELOG.md
  docs/get-started/explorers.md
  docs/zh/get-started/explorers.md
  docs/zh/get-started/wallets.md
Labels: documentation

#2061 R4R: Update explorers list
  docs/get-started/Explorers.md
  docs/zh/get-started/Explorers.md
Labels: documentation

#2060 R4R: Resolve merge conflicts
  go.mod
  go.sum
  version/version.go
Labels: release

#2062 R4R: Clean code and fix golangci error
  Makefile
  app/v1/asset/test_common.go
  app/v1/gov/test_common.go
  app/v1/mock/app.go
  app/v1/mock/app_test.go
  app/v1/rand/test_common.go
  app/v1/service/test_common.go
  app/v1/slashing/app_test.go
  app/v1/stake/app_test.go
  app/v2/htlc/test_common.go
  server/init/init_test.go
  server/mock/app.go
  server/mock/app_test.go
  server/mock/baseapp/baseapp.go
  server/mock/baseapp/helpers.go
  server/mock/baseapp/options.go
  server/mock/baseapp/queryrouter.go
  server/mock/baseapp/router.go
  server/mock/bench_test.go
  server/mock/helpers.go
  server/mock/simulation/params.go
  server/mock/simulation/random_simulate_blocks.go
  server/mock/simulation/transition_matrix.go
  server/mock/simulation/types.go
  server/mock/simulation/util.go
  server/mock/store.go
  server/mock/store_test.go
  server/mock/test_utils.go
  server/mock/tx.go
  tests/lcd/lcd_test.go
  tests/lcd/test_helpers.go
Labels: build, test

#2068 Update for snapshot part
  docs/daemon/snapshot.md
  docs/zh/daemon/snapshot.md
Labels: HTLC, documentation

#2072 R4R: Modify HTLC docs
  docs/cli-client/htlc.md
  docs/zh/cli-client/htlc.md
Labels: HTLC, documentation

#2075 R4R: Update err msgs
  app/v2/coinswap/internal/keeper/keeper.go
  app/v2/coinswap/internal/keeper/swap.go
Labels: coin-swap, enhancement

#2074 R4R: Bump tendermint version
  go.mod
  go.sum
  lite/swagger-ui/swagger.yaml
  version/version.go
Labels: release

#2067 R4R: Fix nil pointer
  server/snapshot.go
Labels: bug

#2073 R4R: Query the block causes panic error
  client/context/context.go
  client/tendermint/rpc/block.go
Labels: CLI, bug

#2077 R4R: Fix bug(write wrong state height)
  server/snapshot.go
Labels: CLI, bug

#2078 R4R: Update lcd api docs
  docs/light-client/CHANGELOG.md
  docs/zh/light-client/CHANGELOG.md
Labels: API, documentation

#2079 R4R: Update gov and snapshot docs
  docs/daemon/snapshot.md
  docs/features/asset.md
  docs/features/governance.md
  docs/zh/daemon/snapshot.md
  docs/zh/features/asset.md
  docs/zh/features/governance.md
Labels: documentation

#2082 Delete test output
  app/v2/coinswap/internal/keeper/keeper_test.go
  app/v2/coinswap/internal/keeper/swap_test.go
Labels: test

#2081 R4R: Update versions
  CHANGELOG.md
  go.mod
  go.sum
  lite/swagger-ui/swagger.yaml
  version/version.go
Labels: release

#2083 R4R: Merge release/v0.16.0 to develop
  CHANGELOG.md
  app/v2/coinswap/internal/keeper/keeper.go
  app/v2/coinswap/internal/keeper/keeper_test.go
  app/v2/coinswap/internal/keeper/swap.go
  app/v2/coinswap/internal/keeper/swap_test.go
  client/context/context.go
  client/tendermint/rpc/block.go
  docs/cli-client/htlc.md
  docs/daemon/snapshot.md
  docs/features/asset.md
  docs/features/governance.md
  docs/light-client/CHANGELOG.md
  docs/zh/cli-client/htlc.md
  docs/zh/daemon/snapshot.md
  docs/zh/features/asset.md
  docs/zh/features/governance.md
  docs/zh/light-client/CHANGELOG.md
  go.mod
  go.sum
  lite/swagger-ui/swagger.yaml
  server/snapshot.go
  version/version.go
Labels: release

#2084 R4R: Update latest version in docs
  docs/features/coinswap.md
  docs/get-started/install.md
  docs/zh/features/coinswap.md
  docs/zh/get-started/install.md
  lite/swagger-ui/swagger.yaml
Labels: documentation

#2101 R4R: Replace circleci with github actions
  .circleci/config.yml
  .github/workflows/BuildAndPublish.yml
  .github/workflows/TestUnit.yml
Labels: build
