Repository irisnet/irishub, pull requests merged in 2019-10, with the labels that each got.

#2024 R4R: Bump Tendermint version to irisnet/tendermint [v0.31.1]
  CHANGELOG.md
  docs/software/How-to-install-irishub.md
  docs/zh/software/How-to-install-irishub.md
  go.mod
  go.sum
  lite/swagger-ui/swagger.yaml
  version/version.go
Labels: tendermint

#2027 R4R: Normalized description
  docs/zh/cli-client/asset.md
  docs/zh/cli-client/bank.md
  docs/zh/cli-client/distribution.md
Labels: documentation

#2029 R4R: Fix HTLC tool method name
  tools/debug/main.go
Labels: CLI

#2031 R4R: Fix CLI test for HTLC
  tests/cli/htlc_test.go
Labels: HTLC, test

#2014 R4R: Add HTLC feature docs
  docs/features/htlc.md
  docs/zh/features/htlc.md
Labels: HTLC, documentation

#2037 R4R: Bump Tendermint version to irisnet/tendermint v0.31.2
  CHANGELOG.md
  docs/software/How-to-install-irishub.md
  docs/zh/software/How-to-install-irishub.md
  go.mod
  go.sum
  lite/swagger-ui/swagger.yaml
  version/version.go
Labels: tendermint

#2040 R4R: Update links
  CONTRIBUTING.md
  README.md
  docs/.vuepress/config.js
  docs/cli-client/keys.md
  docs/cli-client/service.md
  docs/cli-client/tx.md
  docs/features/asset.md
  docs/features/bank.md
  docs/features/htlc.md
  docs/features/random.md
  docs/get-started/install.md
  docs/get-started/mainnet.md
  docs/tools/ledger.md
  docs/tools/monitor.md
  docs/zh/cli-client/asset.md
  docs/zh/cli-client/distribution.md
  docs/zh/cli-client/gov.md
  docs/zh/cli-client/htlc.md
  docs/zh/cli-client/keys.md
  docs/zh/cli-client/rand.md
  docs/zh/cli-client/stake.md
  docs/zh/cli-client/tx.md
  docs/zh/concepts/validator-faq.md
  docs/zh/daemon/intro.md
  docs/zh/daemon/local-testnet.md
  docs/zh/features/asset.md
  docs/zh/features/guardian.md
  docs/zh/features/htlc.md
  docs/zh/features/random.md
  docs/zh/get-started/install.md
  docs/zh/get-started/mainnet.md
  docs/zh/light-client/intro.md
  docs/zh/tools/ledger.md
  docs/zh/tools/monitor.md
Labels: documentation

#2041 R4R: Fix ci failed
  .circleci/config.yml
  docs/.vuepress/config.js
Labels: build

#2039 R4R: Refactor context
  app/baseapp.go
  app/v1/distribution/abci.go
  app/v1/mock/baseapp/baseapp.go
  app/v1/slashing/tick.go
  mock/baseapp/baseapp.go
  modules/slashing/tick.go
  types/context.go
  types/context_counter.go
  types/context_test.go
  types/contexttags.go
  types/tags.go
Labels: enhancement

#2038 R4R: Merge Changelog from master
  CHANGELOG.md
Labels: tendermint

#2018 R4R: The TokenAddition proposal 's InitialSupply should not be set
  app/v1/gov/msgs.go
  app/v1/gov/proposal_util.go
  client/gov/cli/sendtx.go
  client/gov/lcd/sendtx.go
Labels: API, CLI, enhancement, governance

#2042 R4R: Update calculation formula
  app/v2/coinswap/internal/keeper/keeper.go
Labels: coin-swap

#2043 R4R: Update prometheus docs
  docs/tools/monitor.md
  docs/zh/tools/monitor.md
Labels: documentation, metric

#2044 R4R: Update coinswap msgs
  app/v2/coinswap/internal/keeper/keeper.go
  app/v2/coinswap/internal/keeper/swap.go
Labels: coin-swap

#2046 R4R: Fix not find validator set bug
  cmd/iris/main.go
  docs/features/coinswap.md
  docs/zh/features/coinswap.md
  server/reset.go
  server/snapshot.go
Labels: CLI, bug

#2049 R4R: Merge tenderminnt security patch to develop
  CHANGELOG.md
  go.mod
  go.sum
Labels: tendermint

#2047 R4R: Bump tendermint version
  .circleci/config.yml
  CHANGELOG.md
  docs/software/How-to-install-irishub.md
  docs/zh/software/How-to-install-irishub.md
  go.mod
  go.sum
  lite/swagger-ui/swagger.yaml
  version/version.go
Labels: bug, security

#2048 R4R: Bump tendermint version
  .circleci/config.yml
  CHANGELOG.md
  docs/software/How-to-install-irishub.md
  docs/zh/software/How-to-install-irishub.md
  go.mod
  go.sum
  lite/swagger-ui/swagger.yaml
  version/version.go
Labels: bug, security

#2050 R4R: Fix docs
  docs/cli-client/tx.md
  docs/daemon/snapshot.md
  docs/zh/cli-client/tx.md
  docs/zh/daemon/snapshot.md
Labels: documentation
