Repository irisnet/irishub, pull requests merged in 2020-12, with the labels that each got.

#2463 Update gitattributes
  .gitattributes
Labels: build

#2464 Add wasm module
  app/app.go
  cmd/iris/cmd/root.go
  go.mod
  go.sum
  simapp/app.go
Labels: wasm

#2466 Fix docker build
  Dockerfile
  Makefile
  docker-compose.yml
Labels: build

#2470 Update irismod version and swagger doc
  go.mod
  go.sum
  lite/statik/statik.go
  lite/swagger-ui/swagger.yaml
  scripts/protoc-swagger-gen.sh
Labels: API, documentation

#2471 Add wasm swagger doc and cleanup
  lite/config.json
  lite/statik/statik.go
  lite/swagger-ui/swagger.yaml
  lite/swagger_legacy.yaml
  scripts/protoc-swagger-gen.sh
Labels: API, documentation

#2468 Add pagination for APIs
  go.mod
  go.sum
  lite/statik/statik.go
  lite/swagger-ui/swagger.yaml
  modules/guardian/client/cli/query.go
  modules/guardian/keeper/grpc_query.go
  modules/guardian/types/query.pb.go
  modules/guardian/types/query.pb.gw.go
  proto/guardian/query.proto
  scripts/protoc-swagger-gen.sh
Labels: API, enhancement

#2475 Fix query issue_token_base_fee display bug
  cmd/iris/cmd/util.go
Labels: bug

#2476 Refactor swagger docs generation
  Makefile
  docs/cli-client/gov.md
  docs/zh/cli-client/gov.md
  lite/config.json
  lite/cosmos_swagger_legacy.yaml
  lite/irishub_swagger_legacy.yaml
  lite/statik/statik.go
  lite/swagger-ui/swagger.yaml
  scripts/protoc-swagger-gen.sh
Labels: documentation

#2478 Update cosmos-sdk to v0.40.0-rc5
  app/app.go
  cmd/iris/cmd/genaccounts.go
  cmd/iris/cmd/root.go
  cmd/iris/cmd/testnet.go
  cmd/iris/cmd/util.go
  go.mod
  go.sum
  lite/statik/statik.go
  lite/swagger-ui/swagger.yaml
  modules/guardian/client/cli/cli_test.go
  modules/guardian/client/cli/query.go
  modules/guardian/client/cli/tx.go
  modules/guardian/keeper/keeper_test.go
  modules/legacy/types/account.go
  modules/mint/client/cli/query.go
  scripts/protoc-swagger-gen.sh
  simapp/app.go
  simapp/test_helpers.go
  third_party/proto/confio/proofs.proto
Labels: build

#2479 Specify log with cosmos-sdk
  cmd/iris/cmd/root.go
  cmd/iris/main.go
Labels: build
