Repository irisnet/irishub, pull requests merged in 2020-10, with the labels that each got.

#2444 R4R: Update gen swagger
  Makefile
  app/app.go
  app/export.go
  cmd/iris/cmd/genaccounts.go
  cmd/iris/cmd/testnet.go
  go.mod
  go.sum
  lite/config.json
  lite/grpc-gateway/config.json
  lite/grpc-gateway/statik/statik.go
  lite/grpc-gateway/swagger.json
  lite/statik/statik.go
  lite/swagger-ui/swagger.yaml
  lite/swagger.go
  lite/swagger_legacy.yaml
  scripts/protoc-swagger-gen.sh
  simapp/app.go
  simapp/export.go
  simapp/test_helpers.go
  third_party/proto/cosmos_proto/pagination.proto
  third_party/proto/irismod/service.proto
  third_party/proto/tendermint/abci/types/types.proto
  third_party/proto/tendermint/crypto/keys.proto
  third_party/proto/tendermint/crypto/proof.proto
  third_party/proto/tendermint/libs/bits/types.proto
  third_party/proto/tendermint/types/evidence.proto
  third_party/proto/tendermint/types/params.proto
  third_party/proto/tendermint/types/types.proto
  third_party/proto/tendermint/types/validator.proto
  third_party/proto/tendermint/version/types.proto
Labels: API, documentation

#2447 fix bug and clean up
  cmd/iris/cmd/genaccounts.go
  docs/daemon/local-testnet.md
  docs/zh/daemon/local-testnet.md
  go.mod
  go.sum
  modules/mint/module.go
  simapp/test_helpers.go
Labels: bug, documentation

#2450 R4R: Fix service deduct fees and fix gen swagger
  app/app.go
  app/token.go
  go.mod
  go.sum
  lite/config.json
  lite/swagger-ui/swagger.yaml
  scripts/protoc-swagger-gen.sh
  simapp/app.go
Labels: bug

#2448 R4R: Add record cli docs and fix random docs
  docs/cli-client/random.md
  docs/cli-client/record.md
  docs/zh/cli-client/random.md
  docs/zh/cli-client/record.md
Labels: documentation

#2451 update api version
  lite/config.json
  lite/statik/statik.go
  lite/swagger-ui/swagger.yaml
  scripts/protoc-swagger-gen.sh
Labels: API, documentation

#2453 Change profiler to super and remove trustee
  cmd/iris/cmd/testnet.go
  modules/guardian/client/cli/query.go
  modules/guardian/client/cli/tx.go
  modules/guardian/genesis.go
  modules/guardian/handler.go
  modules/guardian/keeper/grpc_query.go
  modules/guardian/keeper/grpc_query_test.go
  modules/guardian/keeper/keeper.go
  modules/guardian/keeper/keeper_test.go
  modules/guardian/keeper/querier.go
  modules/guardian/keeper/querier_test.go
  modules/guardian/types/codec.go
  modules/guardian/types/errors.go
  modules/guardian/types/event.go
  modules/guardian/types/genesis.go
  modules/guardian/types/genesis.pb.go
  modules/guardian/types/guardian.pb.go
  modules/guardian/types/keys.go
  modules/guardian/types/msgs.go
  modules/guardian/types/msgs_test.go
  modules/guardian/types/query.pb.go
  modules/guardian/types/query.pb.gw.go
  modules/guardian/types/types.go
  proto/guardian/genesis.proto
  proto/guardian/guardian.proto
  proto/guardian/query.proto
Labels: enhancement
