Repository irisnet/irishub, pull requests merged in 2020-09, with the labels that each got.

#2409 R4R: Add slashing docs
  docs/cli-client/slashing.md
  docs/features/slashing.md
  docs/zh/cli-client/slashing.md
  docs/zh/features/slashing.md
Labels: documentation, slash

#2413 R4R: Update governance feature docs
  docs/features/governance.md
  docs/zh/features/governance.md
Labels: documentation, governance

#2417 R4R: Update docs random
  docs/cli-client/rand.md
  docs/features/random.md
  docs/zh/cli-client/rand.md
  docs/zh/features/random.md
Labels: documentation, random

#2418 R4R: Update upgrade docs
  docs/features/upgrade.md
  docs/zh/features/upgrade.md
Labels: documentation, upgrade

#2420 R4R: Update docs
  docs/cli-client/gov.md
  docs/cli-client/params.md
  docs/cli-client/rand.md
  docs/cli-client/service.md
  docs/cli-client/stake.md
  docs/cli-client/tx.md
  docs/concepts/coin-type.md
  docs/concepts/fee.md
  docs/concepts/gov-params.md
  docs/concepts/validator-faq.md
  docs/daemon/snapshot.md
  docs/features/bank.md
  docs/features/distribution.md
  docs/features/guardian.md
  docs/features/mint.md
  docs/features/stake.md
  docs/get-started/mainnet.md
  docs/light-client/CHANGELOG.md
  docs/tools/iristool.md
  docs/tools/ledger.md
  docs/zh/cli-client/gov.md
  docs/zh/cli-client/params.md
  docs/zh/cli-client/rand.md
  docs/zh/cli-client/service.md
  docs/zh/cli-client/stake.md
  docs/zh/cli-client/tx.md
  docs/zh/concepts/coin-type.md
  docs/zh/concepts/fee.md
  docs/zh/concepts/gov-params.md
  docs/zh/concepts/validator-faq.md
  docs/zh/daemon/local-testnet.md
  docs/zh/features/bank.md
  docs/zh/features/distribution.md
  docs/zh/features/guardian.md
  docs/zh/features/mint.md
  docs/zh/features/stake.md
  docs/zh/get-started/mainnet.md
  docs/zh/light-client/CHANGELOG.md
  docs/zh/light-client/intro.md
  docs/zh/tools/iristool.md
  docs/zh/tools/ledger.md
Labels: documentation

#2422 more token conversion config
  cmd/iris/cmd/util.go
  go.mod
  go.sum
Labels: client

#2423 update service and token modules
  go.mod
  go.sum
Labels: build

#2424 Link to a specified version
  docs/get-started/install.md
  docs/zh/get-started/install.md
Labels: documentation

#2425 Merge v0.16.3 commits and clean up
  CHANGELOG.md
  docs/cli-client/bank.md
  docs/cli-client/distribution.md
  docs/cli-client/htlc.md
  docs/cli-client/intro.md
  docs/cli-client/keys.md
  docs/cli-client/oracle.md
  docs/cli-client/service.md
  docs/cli-client/staking.md
  docs/cli-client/token.md
  docs/concepts/general-concepts.md
  docs/concepts/gov-params.md
  docs/concepts/validator-faq.md
  docs/features/bank.md
  docs/features/staking.md
  docs/get-started/install.md
  docs/zh/cli-client/bank.md
  docs/zh/cli-client/distribution.md
  docs/zh/cli-client/htlc.md
  docs/zh/cli-client/intro.md
  docs/zh/cli-client/keys.md
  docs/zh/cli-client/oracle.md
  docs/zh/cli-client/staking.md
  docs/zh/cli-client/token.md
  docs/zh/concepts/gov-params.md
  docs/zh/concepts/validator-faq.md
  docs/zh/daemon/local-testnet.md
  docs/zh/features/bank.md
  docs/zh/features/staking.md
  docs/zh/get-started/install.md
  lite/swagger-ui/swagger.yaml
Labels: documentation

#2428 Use file as input
  modules/oracle/client/cli/tx.go
Labels: CLI, enhancement

#2439 Audit js dependency
  docs/package-lock.json
Labels: build

#2443 Update install.md ENV variable script
  docs/get-started/install.md
  docs/zh/get-started/install.md
Labels: documentation

#2434 Document cleanup
  docs/cli-client/bank.md
  docs/cli-client/distribution.md
  docs/cli-client/htlc.md
  docs/cli-client/nft.md
  docs/cli-client/oracle.md
  docs/cli-client/random.md
  docs/cli-client/service.md
  docs/cli-client/slashing.md
  docs/features/bank.md
  docs/features/governance.md
  docs/features/guardian.md
  docs/features/htlc.md
  docs/features/nft.md
  docs/features/oracle.md
  docs/features/service.md
  docs/zh/cli-client/bank.md
  docs/zh/cli-client/distribution.md
  docs/zh/cli-client/htlc.md
  docs/zh/cli-client/nft.md
  docs/zh/cli-client/oracle.md
  docs/zh/cli-client/random.md
  docs/zh/cli-client/service.md
  docs/zh/daemon/snapshot.md
  docs/zh/features/bank.md
  docs/zh/features/distribution.md
  docs/zh/features/governance.md
  docs/zh/features/guardian.md
  docs/zh/features/htlc.md
  docs/zh/features/nft-metadata.json
  docs/zh/features/nft.md
  docs/zh/features/oracle.md
  docs/zh/features/service.md
Labels: documentation
