Repository irisnet/irishub, pull requests merged in 2020-08, with the labels that each got.

#2391 update swagger-ui
  .gitignore
  cmd/iris/main.go
  lite/statik/statik.go
  lite/swagger-ui/cosmos-swagger.yaml
  lite/swagger-ui/swagger.yaml
Labels: API

#2394 R4R: Bump ledger-cosmos-go version
  CHANGELOG.md
  docs/get-started/install.md
  docs/zh/get-started/install.md
  go.mod
  go.sum
  lite/swagger-ui/swagger.yaml
  version/version.go
Labels: bug, client

#2157 R4R: Refactor coin type
  cmd/iris/cmd/root.go
  cmd/iris/cmd/util.go
  go.mod
  go.sum
  types/coin_type.go
  types/coin_type_test.go
Labels: CLI

#2398 R4R: Update random cli docs
  docs/cli-client/rand.md
  docs/zh/cli-client/rand.md
Labels: CLI, documentation, random

#2396 R4R: Update params command docs
  docs/cli-client/params.md
  docs/zh/cli-client/params.md
Labels: documentation

#2402 R4R: Update gov docs
  docs/cli-client/gov.md
  docs/zh/cli-client/gov.md
Labels: documentation

#2399 R4R: Update docs service
  docs/cli-client/service.md
  docs/zh/cli-client/service.md
Labels: CLI, documentation, service

#2410 Bug fix and code clean
  cmd/iris/cmd/testnet.go
  go.mod
  go.sum
  modules/guardian/types/guardian.pb.go
  modules/guardian/types/types.go
  modules/random/client/cli/query.go
  modules/random/types/msgs_test.go
  modules/random/types/random.pb.go
  proto/guardian/guardian.proto
  proto/random/random.proto
Labels: bug, build

#2400 R4R: Update staking docs
  docs/cli-client/stake.md
  docs/zh/cli-client/stake.md
Labels: documentation, stake

#2401 R4R: Update tendermint docs
  docs/cli-client/status.md
  docs/cli-client/tendermint.md
  docs/cli-client/tx.md
  docs/cli-client/upgrade.md
  docs/zh/cli-client/status.md
  docs/zh/cli-client/tendermint.md
  docs/zh/cli-client/tx.md
  docs/zh/cli-client/upgrade.md
Labels: documentation

#2404 R4R: Update feature docs
  docs/concepts/gov-params.md
  docs/features/asset.md
  docs/features/bank.md
  docs/features/coinswap.md
  docs/features/distribution.md
  docs/features/guardian.md
  docs/features/htlc.md
  docs/features/nft-metadata.json
  docs/features/nft.md
  docs/features/service.md
  docs/features/stake.md
  docs/features/token.md
  docs/get-started/install.md
  docs/zh/concepts/gov-params.md
  docs/zh/features/asset.md
  docs/zh/features/bank.md
  docs/zh/features/guardian.md
  docs/zh/features/htlc.md
  docs/zh/features/nft-metadata.json
  docs/zh/features/nft.md
  docs/zh/features/service.md
  docs/zh/features/stake.md
  docs/zh/features/token.md
  docs/zh/get-started/install.md
Labels: documentation
