Repository irisnet/irishub, pull requests merged in 2021-01, with the labels that each got.

#2481 Register legacy evidence
  app/encoding.go
Labels: bug

#2480 Implement wasm CustomEncoder
  app/app.go
  app/wasm_custom_encoder.go
  app/wasm_custom_encoder_test.go
Labels: wasm

#2484 Bump cosmos-sdk to v0.40.0
  go.mod
  go.sum
  simapp/test_helpers.go
Labels: dependencies

#2483 Revert wasm commits
  Dockerfile
  app/app.go
  app/wasm_custom_encoder.go
  app/wasm_custom_encoder_test.go
  cmd/iris/cmd/root.go
  cmd/iris/main.go
  docs/cli-client/wasm.md
  docs/zh/cli-client/wasm.md
  go.mod
  go.sum
  lite/config.json
  lite/swagger-ui/swagger.yaml
  modules/legacy/client/rest/bank/query.go
  scripts/protoc-swagger-gen.sh
  simapp/app.go
Labels: wasm

#2159 Migrate genesis state to v1.0.0
  app/encoding.go
  cmd/iris/cmd/root.go
  migrate/README.md
  migrate/migrate.go
  migrate/privval/old_file.go
  migrate/privval/old_file_test.go
  migrate/scripts/privValUpgrade.go
  migrate/v0_16/account.go
  migrate/v0_16/asset/genesis.go
  migrate/v0_16/auth/genesis.go
  migrate/v0_16/coinswap/genesis.go
  migrate/v0_16/distribution/genesis.go
  migrate/v0_16/genesis.go
  migrate/v0_16/gov/genesis.go
  migrate/v0_16/guardian/genesis.go
  migrate/v0_16/htlc/genesis.go
  migrate/v0_16/mint/genesis.go
  migrate/v0_16/rand/genesis.go
  migrate/v0_16/service/genesis.go
  migrate/v0_16/slashing/genesis.go
  migrate/v0_16/stake/genesis.go
  migrate/v0_16/types/address.go
  migrate/v0_16/types/codec.go
  migrate/v0_16/types/coin.go
  migrate/v0_16/types/config.go
  migrate/v0_16/types/int.go
  migrate/v0_16/upgrade/genesis.go
Labels: state

#2491 Fix irishub build for v1.0.0
  Makefile
  app/ante.go
  app/app.go
  app/encoding.go
  app/export.go
  app/params/doc.go
  app/params/encoding.go
  app/params/params.go
  app/params/proto.go
  app/params/weights.go
  app/replay.go
  cmd/iris/cmd/root.go
  lite/statik/statik.go
  lite/swagger-ui/swagger.yaml
  migrate/README.md
  migrate/v0_16/genesis.go
  modules/mint/types/genesis.pb.go
  proto/mint/genesis.proto
Labels: build

#2496 Fix migrate
  migrate/README.md
  migrate/migrate.go
Labels: bug, documentation

#2502 Release v1.0.0-rc0
  CHANGELOG.md
  go.mod
  go.sum
  lite/statik/statik.go
  lite/swagger-ui/swagger.yaml
  scripts/protoc-swagger-gen.sh
Labels: dependencies, release

#2506 Add upgrade module command document
  docs/cli-client/upgrade.md
  docs/package-lock.json
  docs/package.json
  docs/zh/cli-client/upgrade.md
Labels: CLI, documentation

#2512 Add genesis and msgs check
  modules/guardian/genesis.go
  modules/guardian/types/msgs.go
Labels: enhancement

#2515 Bump cosmos-sdk version to v0.40.1
  go.mod
  go.sum
  lite/statik/statik.go
  lite/swagger-ui/swagger.yaml
  scripts/protoc-swagger-gen.sh
Labels: dependencies

#2517 Improve swagger doc
  lite/config.json
  lite/statik/statik.go
  lite/swagger-ui/swagger.yaml
  scripts/protoc-swagger-gen.sh
Labels: documentation

#2518 Move abandoned tokens to communityTax
  migrate/migrate.go
Labels: enhancement

#2522 Fix migrate script and add msg normalization
  cmd/iris/cmd/util.go
  go.mod
  go.sum
  migrate/migrate.go
Labels: enhancement

#2529 Bump irismod to latest version
  go.mod
  go.sum
  lite/statik/statik.go
  lite/swagger-ui/swagger.yaml
  scripts/protoc-swagger-gen.sh
Labels: dependencies

#2534 Upgrade irismod version
  go.mod
  go.sum
  scripts/protoc-swagger-gen.sh
Labels: dependencies

#2532 Release v1.0.0-rc1
  CHANGELOG.md
  go.mod
  go.sum
  scripts/protoc-swagger-gen.sh
Labels: release

#2530 Fix htlc export order bug
  app/v2/export.go
Labels: bug

#2538 Add v0.16.4 changelog
  CHANGELOG.md
Labels: release
