Repository irisnet/irishub, pull requests merged in 2021-02, with the labels that each got.

#2541 Bump cosmos-sdk to v0.41.0
  go.mod
  go.sum
Labels: dependencies

#2540 Update v0.16.4 version
  version/version.go
Labels: release

#2542 Migrate withdraw infos
  CHANGELOG.md
  migrate/migrate.go
Labels: bug, distr

#2543 Upgrade irismod to latest version
  app/app.go
  go.mod
  go.sum
  simapp/app.go
Labels: dependencies

#2545 Update irismod version
  go.mod
  go.sum
Labels: dependencies

#2523 Fix err check and improve code
  go.sum
  keystore/keystore.go
  migrate/v0_16/stake/genesis.go
  modules/guardian/module.go
  modules/mint/module.go
Labels: enhancement

#2536 Fix coin convert invalid
  cmd/iris/cmd/root.go
  cmd/iris/cmd/util.go
Labels: CLI, enhancement

#2511 Add auth and mint cli docs
  docs/cli-client/auth.md
  docs/cli-client/mint.md
  docs/zh/cli-client/auth.md
  docs/zh/cli-client/mint.md
Labels: documentation

#2548 Add ante for service
  app/ante.go
  app/decorators.go
  app/token_check.go
  modules/guardian/types/errors.go
Labels: enhancement, service

#2551 Add service ante
  app/ante.go
  app/decorators.go
Labels: service

#2550 Update ledger document
  docs/pics/ledger-manager.png
  docs/pics/ledger-search.png
  docs/tools/ledger.md
  docs/zh/pics/ledger-manager.png
  docs/zh/pics/ledger-search.png
  docs/zh/tools/ledger.md
Labels: documentation, ledger

#2527 Update gen swagger
  scripts/protoc-swagger-gen.sh
Labels: API

#2520 Add API docs
  docs/endpoints/grpc-client.md
  docs/endpoints/grpc-rest.md
  docs/endpoints/intro.md
  docs/endpoints/legacy-rest.md
  docs/endpoints/proto-docs.md
  docs/endpoints/protodoc-markdown.tmpl
  docs/endpoints/sdk.md
  docs/light-client/CHANGELOG.md
  docs/light-client/intro.md
  docs/zh/endpoints/grpc-client.md
  docs/zh/endpoints/grpc-rest.md
  docs/zh/endpoints/intro.md
  docs/zh/endpoints/legacy-rest.md
  docs/zh/endpoints/proto-docs.md
  docs/zh/endpoints/sdk.md
  docs/zh/light-client/CHANGELOG.md
  docs/zh/light-client/intro.md
  scripts/protoc-swagger-gen.sh
Labels: API, documentation

#2552 Update irismod version&swagger
  docs/endpoints/proto-docs.md
  docs/zh/endpoints/proto-docs.md
  go.mod
  go.sum
  lite/statik/statik.go
  lite/swagger-ui/swagger.yaml
  scripts/protoc-swagger-gen.sh
Labels: dependencies

#2553 Fix migrate and update migration docs
  docs/migration/README.md
  docs/migration/keys.md
  docs/zh/migration/README.md
  docs/zh/migration/keys.md
  migrate/keys.md
  migrate/migrate.go
Labels: documentation, enhancement

#2554 Update kms docs
  docs/daemon/local-testnet.md
  docs/tools/kms.md
  docs/tools/priv_validator_state.json
  docs/zh/tools/kms.md
Labels: documentation

#2555 Update sdk doc link
  docs/zh/endpoints/sdk.md
Labels: documentation

#2556 Delete ledger option
  docs/tools/kms.md
  docs/zh/tools/kms.md
  docs/zh/tools/kms/kms.md
Labels: documentation

#2528 Update docs/genesis-file
  docs/concepts/genesis-file.md
  docs/zh/concepts/genesis-file.md
Labels: documentation

#2507 Update nft features doc
  docs/features/nft.md
  docs/zh/features/nft.md
Labels: documentation

#2513 Update upgrade feature document
  docs/features/upgrade.md
  docs/zh/features/upgrade.md
Labels: documentation

#2526 Update client doc into
  docs/cli-client/intro.md
  docs/zh/cli-client/intro.md
Labels: documentation

#2533 Update tools docs
  docs/cli-client/debug.md
  docs/tools/iristool.md
  docs/zh/cli-client/debug.md
  docs/zh/tools/iristool.md
Labels: documentation

#2547 Add total&rewards command for coin converter
  cmd/iris/cmd/util.go
Labels: CLI, enhancement

#2557 Update crisis constant fee
  migrate/migrate.go
Labels: enhancement

#2537 Update gov-params.md
  docs/concepts/gov-params.md
  docs/zh/concepts/gov-params.md
Labels: documentation

#2558 Update irismod version
  go.mod
  go.sum
  scripts/protoc-swagger-gen.sh
Labels: dependencies

#2560 Release v1.0.0-rc2
  CHANGELOG.md
  app/ante.go
  go.mod
  go.sum
  scripts/protoc-swagger-gen.sh
Labels: release

#2561 Update upgrade docs
  docs/features/upgrade.md
  docs/zh/features/upgrade.md
Labels: documentation

#2563 Cleanup proto
  docs/endpoints/proto-docs.md
  docs/zh/endpoints/proto-docs.md
  go.mod
  go.sum
  lite/swagger-ui/swagger.yaml
  modules/guardian/types/genesis.pb.go
  modules/guardian/types/query.pb.go
  modules/guardian/types/tx.pb.go
  modules/mint/types/genesis.pb.go
  modules/mint/types/mint.pb.go
  modules/mint/types/query.pb.go
  proto/guardian/genesis.proto
  proto/guardian/query.proto
  proto/guardian/tx.proto
  proto/mint/genesis.proto
  proto/mint/mint.proto
  proto/mint/query.proto
  scripts/protoc-swagger-gen.sh
Labels: enhancement

#2565 Update irismod version&swagger
  go.mod
  go.sum
  lite/statik/statik.go
  scripts/protoc-swagger-gen.sh
Labels: dependencies

#2566 Update community channels
  docs/concepts/validator-faq.md
  docs/zh/concepts/validator-faq.md
Labels: documentation

#2567 Release v1.0.0
  CHANGELOG.md
  go.mod
  go.sum
  scripts/protoc-swagger-gen.sh
Labels: dependencies, release

#2571 Release v1.0.1
  CHANGELOG.md
  Dockerfile
  docs/endpoints/proto-docs.md
  docs/migration/README.md
  docs/migration/keys.md
  docs/zh/endpoints/proto-docs.md
  docs/zh/migration/README.md
  docs/zh/migration/keys.md
  go.mod
  go.sum
  lite/config.json
  lite/statik/statik.go
  lite/swagger-ui/swagger.yaml
  scripts/protoc-swagger-gen.sh
Labels: dependencies, release

#2572 Do not modify reDnmString
  Makefile
Labels: build

#2573 Bump cosmos-sdk version to v0.41.3
  CHANGELOG.md
  go.mod
  go.sum
  scripts/protoc-swagger-gen.sh
Labels: dependencies

#2569 Update migrate docs
  docs/migration/README.md
  docs/zh/migration/README.md
Labels: documentation

#2574 Specify initial height
  docs/migration/README.md
  docs/zh/migration/README.md
Labels: documentation

#2509 Update get-started doc
  docs/daemon/export.md
  docs/features/governance.md
  docs/get-started/install.md
  docs/get-started/mainnet.md
  docs/get-started/testnet.md
  docs/zh/cli-client/gov.md
  docs/zh/get-started/install.md
  docs/zh/get-started/mainnet.md
  docs/zh/get-started/testnet.md
Labels: documentation

#2576 Update vuepress config
  docs/.vuepress/config.js
Labels: documentation

#2578 Update testnet instructions
  docs/get-started/testnet.md
  docs/zh/get-started/testnet.md
Labels: documentation

#2580 Fix some details
  docs/endpoints/legacy-rest.md
  docs/zh/endpoints/legacy-rest.md
Labels: documentation

#2583 Fix endpoints doc
  docs/.vuepress/config.js
  docs/endpoints/grpc-client.md
  docs/endpoints/grpc-rest.md
  docs/endpoints/intro.md
  docs/endpoints/legacy-rest.md
  docs/endpoints/proto-docs.md
  docs/endpoints/protodoc-markdown.tmpl
  docs/endpoints/sdk.md
  docs/package-lock.json
  docs/zh/endpoints/grpc-client.md
  docs/zh/endpoints/grpc-rest.md
  docs/zh/endpoints/intro.md
  docs/zh/endpoints/legacy-rest.md
  docs/zh/endpoints/proto-docs.md
  docs/zh/endpoints/sdk.md
Labels: documentation

#2582 Fix testnet links
  docs/get-started/testnet.md
  docs/zh/get-started/testnet.md
Labels: documentation
