Repository irisnet/irishub, pull requests merged in 2021-08, with the labels that each got.

#2640 fix the staking.md
  docs/zh/features/staking.md
Labels: documentation

#2645 Version bumps, non-breaking
  go.mod
  go.sum
Labels: dependencies

#2647 Fix zh/features/governance.md
  docs/zh/features/governance.md
Labels: documentation

#2643 Fix nft metadata link
  docs/features/nft.md
  docs/zh/features/nft.md
Labels: documentation

#2648 Upgrade coinswap
  app/app.go
  app/decorators.go
  go.mod
  go.sum
Labels: dependencies

#2651 Fix zh/features/governance.md
  docs/zh/features/governance.md
Labels: documentation

#2652 Update coin denom
  app/app.go
Labels: bug

#2653 Update irismod version
  go.mod
  go.sum
Labels: dependencies

#2654 Fix command typo
  docs/features/service.md
  docs/zh/features/service.md
Labels: bug, documentation

#2655 Fix cosmos-sdk v0.42.9 upgrade
  app/app.go
  simapp/app.go
Labels: bug

#2657 Update irismod version
  go.mod
  go.sum
Labels: dependencies

#2658 Update irismod version and proto docs
  docs/endpoints/proto-docs.md
  docs/zh/endpoints/proto-docs.md
  go.mod
  go.sum
  lite/cosmos_swagger_legacy.yaml
  lite/swagger-ui/swagger.yaml
  scripts/protoc-swagger-gen.sh
Labels: dependencies

#2656 Fix testnet
  docs/get-started/testnet.md
  docs/zh/get-started/testnet.md
Labels: documentation

#2659 Update swagger doc
  lite/statik/statik.go
Labels: documentation

#2660 Fix-large-unit-conversion-bug
  cmd/iris/cmd/util.go
Labels: bug

#2661 Update irismod dependecy
  go.mod
  go.sum
Labels: dependencies

#2665 Add farm pagination
  go.mod
  go.sum
Labels: dependencies
