Repository irisnet/irishub, pull requests merged in 2021-03, with the labels that each got.

#2588 Bump up sdk and irismod version
  app/app.go
  go.mod
  go.sum
  lite/cosmos_swagger_legacy.yaml
  lite/statik/statik.go
  lite/swagger-ui/swagger.yaml
  scripts/protoc-swagger-gen.sh
  simapp/app.go
Labels: dependencies

#2590 Bump cosmos-sdk version to 0.42.1
  CHANGELOG.md
  docs/endpoints/proto-docs.md
  docs/zh/endpoints/proto-docs.md
  go.mod
  go.sum
  lite/cosmos_swagger_legacy.yaml
  lite/statik/statik.go
  lite/swagger-ui/swagger.yaml
  scripts/protoc-swagger-gen.sh
Labels: dependencies

#2593 Update Get Started Docs
  README.md
  docs/concepts/validator-faq.md
  docs/get-started/explorers.md
  docs/get-started/testnet.md
  docs/get-started/wallets.md
  docs/zh/concepts/validator-faq.md
  docs/zh/get-started/explorers.md
  docs/zh/get-started/testnet.md
  docs/zh/get-started/wallets.md
Labels: documentation

#2592 Bump up irismod and cosmos-sdk version, add migrate logic
  .gitignore
  app/ante.go
  app/app.go
  app/app_test.go
  app/decorators.go
  app/export.go
  cmd/iris/cmd/root.go
  docs/endpoints/proto-docs.md
  docs/zh/endpoints/proto-docs.md
  go.mod
  go.sum
  lite/statik/statik.go
  lite/swagger-ui/swagger.yaml
  migrate/htlc/htlc.pb.go
  migrate/htlc/keys.go
  migrate/htlc/migrate.go
  migrate/migrate.go
  migrate/privval/old_file.go
  migrate/privval/old_file_test.go
  migrate/scripts/privValUpgrade.go
  migrate/service/migrate.go
  migrate/v0_16/account.go
  migrate/v0_16/asset/genesis.go
  migrate/v0_16/auth/genesis.go
  migrate/v0_16/coinswap/genesis.go
  migrate/v0_16/distribution/genesis.go
  migrate/v0_16/genesis.go
  migrate/v0_16/gov/genesis.go
  migrate/v0_16/guardian/genesis.go
  migrate/v0_16/htlc/genesis.go
  migrate/v0_16/mint/genesis.go
  migrate/v0_16/rand/genesis.go
  migrate/v0_16/service/genesis.go
  migrate/v0_16/slashing/genesis.go
  migrate/v0_16/stake/genesis.go
  migrate/v0_16/types/address.go
  migrate/v0_16/types/codec.go
  migrate/v0_16/types/coin.go
  migrate/v0_16/types/config.go
  migrate/v0_16/types/int.go
  migrate/v0_16/upgrade/genesis.go
  scripts/protoc-swagger-gen.sh
  simapp/app.go
  simapp/encoding.go
  simapp/export.go
  simapp/genesis.go
  simapp/test_helpers.go
Labels: dependencies, enhancement, upgrade

#2595 Update migrate service
  go.mod
  go.sum
  migrate/service/migrate.go
  scripts/protoc-swagger-gen.sh
Labels: upgrade

#2597 Fix migrate
  migrate/service/migrate.go
Labels: bug, upgrade

#2596 Update htlt preset params
  migrate/htlc/migrate.go
Labels: upgrade

#2599 Release v1.1.0-rc0
  CHANGELOG.md
  lite/config.json
  lite/statik/statik.go
  lite/swagger-ui/swagger.yaml
Labels: release

#2600 R4R: Update docs dependencies
  docs/package-lock.json
  docs/package.json
Labels: documentation

#2603 Ensure account permissions
  go.mod
  go.sum
  migrate/htlc/migrate.go
Labels: bug

#2604 Update v1.1 docs
  docs/cli-client/htlc.md
  docs/cli-client/params.md
  docs/features/htlc.md
  docs/zh/cli-client/htlc.md
  docs/zh/cli-client/params.md
  docs/zh/features/htlc.md
Labels: documentation

#2605 Release v1.1.0
  CHANGELOG.md
  docs/endpoints/proto-docs.md
  docs/zh/endpoints/proto-docs.md
  go.mod
  go.sum
  lite/config.json
  lite/statik/statik.go
  lite/swagger-ui/swagger.yaml
  scripts/protoc-swagger-gen.sh
Labels: dependencies, release

#2606 Update date
  CHANGELOG.md
Labels: release

#2607 Update v1.1.0 docs
  docs/get-started/install.md
  docs/migration/README.md
  docs/migration/keys.md
  docs/zh/get-started/install.md
  docs/zh/migration/README.md
  docs/zh/migration/keys.md
Labels: documentation
